"""initial_migration_baseline

Revision ID: 2026_02_20_001
Revises: 
Create Date: 2026-02-20 10:43:52.915524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2026_02_20_001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_idempotency_keys_id'), table_name='todo_idempotency_keys')
    op.drop_index(op.f('ix_todo_idempotency_keys_idempotency_key'), table_name='todo_idempotency_keys')
    op.drop_table('todo_idempotency_keys')
    op.drop_index(op.f('ix_todos_id'), table_name='todos')
    op.drop_table('todos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False),
    sa.Column('deleted_at', sa.DATETIME(), server_default=sa.text('(NULL)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todos_id'), 'todos', ['id'], unique=False)
    op.create_table('todo_idempotency_keys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('idempotency_key', sa.VARCHAR(length=50), nullable=False),
    sa.Column('todo_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['todo_id'], ['todos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_idempotency_keys_idempotency_key'), 'todo_idempotency_keys', ['idempotency_key'], unique=1)
    op.create_index(op.f('ix_todo_idempotency_keys_id'), 'todo_idempotency_keys', ['id'], unique=False)
    # ### end Alembic commands ###
