"""add_deleted_at_to_todos

Revision ID: 2026_02_21_003
Revises: 2026_02_21_002
Create Date: 2026-02-21 15:56:23.031778

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2026_02_21_003"
down_revision: Union[str, Sequence[str], None] = "2026_02_21_002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "todos", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("todos", "deleted_at")
    # ### end Alembic commands ###
