"""drop_todo_idempotency_keys

Revision ID: 2026_02_20_002
Revises: 2026_02_20_001
Create Date: 2026-02-20 11:18:32.515112

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "2026_02_20_002"
down_revision: Union[str, Sequence[str], None] = "2026_02_20_001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
