"""make_is_completed_not_nullable

Revision ID: 2026_02_21_004
Revises: 2026_02_21_003
Create Date: 2026-02-21 16:44:41.670619

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2026_02_21_004"
down_revision: Union[str, Sequence[str], None] = "2026_02_21_003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("todos") as batch_op:
        batch_op.alter_column(
            "is_completed",
            existing_type=sa.Boolean(),
            nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("todos") as batch_op:
        batch_op.alter_column(
            "is_completed",
            existing_type=sa.Boolean(),
            nullable=True,
        )
    # ### end Alembic commands ###
