"""initial_migration_baseline

Revision ID: 2026_02_20_001
Revises:
Create Date: 2026-02-20 11:10:05.957457

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "2026_02_20_001"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
